version: "3.7"

secrets:
  proxy_password:
    file: ./secrets/.proxy_password

# See https://stackoverflow.com/questions/29261811/use-docker-compose-env-variable-in-dockerbuild-file
services:

  webui:
    secrets:
      - proxy_password
    build:
      context: ./webui
      dockerfile: Dockerfile.prod
      args: # from env_file
        UNIQUE_NAMESPACE: ${UNIQUE_NAMESPACE}
        IMAGE_REPOSITORY: ${IMAGE_REPOSITORY}
        PROXY_USER: ${PROXY_USER}
        PROXY_PASSWORD: ${PROXY_PASSWORD}
        PROXY_FQDN: ${PROXY_FQDN}
        PROXY_PORT: ${PROXY_PORT}
        NODE_ENV: production
    env_file:
      - ./prod/.env   
    container_name: ${UNIQUE_NAMESPACE}-webui-prod
    security_opt:
      - no-new-privileges:true
    ports:
      - "80:80"
    # environment:
    #  - PROXY_PASSWORD='/run/secrets/proxy_password'
